version: 1.0.{build}
clone_folder: c:\project
environment:
  matrix:
  - HAXE_VERSION: 3.4.3
    PYTHON_VERSION: 27
  - HAXE_VERSION: 3.4.3
    PYTHON_VERSION: 36
  - HAXE_VERSION: latest
    PYTHON_VERSION: 27
  - HAXE_VERSION: latest
    PYTHON_VERSION: 36
build: off
test_script:
- ps: >-
    & C:\\Python${env:PYTHON_VERSION}\\python.exe handyhaxe.py --haxe-version=${env:HAXE_VERSION} --cmd haxe -version
    & C:\\Python${env:PYTHON_VERSION}\\python.exe handyhaxe.py --haxe-version=${env:HAXE_VERSION} --cmd haxe -main HelloWorld -neko out.n
    & C:\\Python${env:PYTHON_VERSION}\\python.exe handyhaxe.py --haxe-version=${env:HAXE_VERSION} --cmd neko out.n
   
