version: 1.0.{build}
clone_folder: c:\project
environment:
  matrix:
  - HAXE_VERSION: 3.4.3
    PYTHON_VERSION: 27
  - HAXE_VERSION: 3.4.3
    PYTHON_VERSION: 36
  - HAXE_VERSION: latest
    PYTHON_VERSION: 27
  - HAXE_VERSION: latest
    PYTHON_VERSION: 36
build: off
test_script:
  - "SET PATH=C:\\Python%PYTHON_VERSION%;%PATH%"    
  - "python handyhaxe.py --haxe-version=%HAXE_VERSION% --cmd haxe -version"
  - "python handyhaxe.py --haxe-version=%HAXE_VERSION% --cmd haxe --cwd samples -main HelloWorld -neko out.n"
  - "python handyhaxe.py --haxe-version=%HAXE_VERSION% --cmd neko samples/out.n"
   
